### ISSUE TITLE
Sphinx documentation to RTD

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zc.intid#11]
Mostly autogenerated, with the exception perhaps of a deeper explanation of benefits and differences from zope.intid (see a long docstring in #10).

**Comment by jamadden** [comment]
See http://zcintid.readthedocs.io

Some expansion and adjustment is needed after #10 is merged.

**Comment by jamadden** [comment]
Note that using sphinx markup in CHANGES.rst means it can't be auto-included in the PyPI page.

**Comment by icemac** [comment]
@jamadden I only see the usage of `:issue:` there. Replacing it it actual ReST style links could allow to use CHANGES.rst on the PyPI page. But maybe it is enough to have a link on the PyPI page pointing to RTD to allow the easier Sphinx style ReST in CHANGES.rst.

**Comment by jamadden** [comment]
@icemac I do appreciate that removing CHANGES from the PyPI page is, well, a change 😉  I'm willing to revert that, but I'd like to share my rationale.

Wearing my maintainer hat, I have found that being able to use Sphinx markup like `:issue:`, `:doc:`, and intersphink links has reduced the burden of maintaining a useful, well-linked changelog that is also easy to read and edit in its RST form. As a user, I appreciate having as many relevant links in a changelog as possible so I can explore related issues in depth.

Doing some crystal ball gazing, the design direction of Warehouse (the PyPI replacement) is strongly de-emphasizing the package-provided longdescription. Even on a high-res monitor, you can get only a few paragraphs of prose "above the fold" there before viewers have to start scrolling. Currently on PyPI, zc.intid's entire document (including *both* change notes) is easily visible without scrolling in a browser window that's a third the height of my screen. On Warehouse, in contrast, a full-height window only just manages to show the top note. Warehouse also moves the "home page" link to a prominent position near the top left. All of that suggests to me that projects are going to be better off hosting their changenotes with a prominent link from their home page and in the first few paragraphs of their description, rather than trying to embed them.

**Comment by icemac** [comment]
@jamadden +1 for having the change log easily accessible from PyPI and easily maintainable.

The interesting thing about PyPI is the [Release History link](https://pypi.org/project/zc.intid/#history). It currently only contains version numbers and placeholder text. It will be interesting which approach PyPI will come up with to replace the placeholder text. :)
