### ISSUE TITLE
PyPI releases

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zc.intid#12]
Hi @freddrake ! I've been doing a substantial amount of work on zc.intid recently, adding Python 3 support and so on. Sometime in the near-ish future when this is finished it would be good to push a 2.0 release to PyPI. 

I think you're the owner of the PyPI project (fdrake). Are you still interested in managing PyPI releases? If not, would you be willing to give me (jamadden) access? (I have release access for gevent, RelStorage, z3c.autoinclude, z3c.schema, zc.zodbdgc and zope.intid.)

Thanks!

**Comment by jamadden** [comment]
@tseaver Would you by chance know how to contact the listed maintainers of the PyPI project (fdrake, patricks)?

**Comment by tseaver** [comment]
@jamadden AFAIK the e-mail address on @freddrake's profile page is current.  I believe the PyPI `patricks` is the same as @kilink here.

**Comment by kilink** [comment]
@jamadden I've added you as an owner of zc.intid.

meta-note: why doesn't PyPI have group-based access control...

**Comment by jamadden** [comment]
Thank you!

**Comment by mgedmin** [comment]
AFAIK group-based access control is on the roadmap for Warehouse, the new version of PyPI software that might reach production in a year or two, hopefully...
